### ISSUE TITLE
Browser version only shows a white page!

### ISSUE THREAD

**Issue by ffleurey** [ffleurey/ThingML-PongTutorial#1]
Not sure what happened but I belive that I am using the latest version of the compiler on BreakoutBrowser.thingml

**Comment by brice-morin** [comment]
Seems like it works for me... with Firefox. Difficulty increases as it should according to new implementation (ball speed only, instead of increasing the whole game)

**Comment by brice-morin** [comment]
Should be fixed. I updated to new annotation...
