### ISSUE TITLE
Posix version seems broken

### ISSUE THREAD

**Issue by brice-morin** [ffleurey/ThingML-PongTutorial#3]
Posix version seems broken with latest version of ThingML (if it ever worked...?)

**Comment by ffleurey** [comment]
It use to work. What is the symptom you get? ThingML compilation error or error when running make? It may require installing some libraries (SDL).

**Comment by brice-morin** [comment]
It compiles and run. It works fine until the ball is lost. From that point, it starts doing strange things, like the ball is not really considered lost by the game, etc. Seems like other versions work OK.

**Comment by brice-morin** [comment]
well, it might be related to internal ports... since the game uses an internal port to notify itself that the ball has been lost

**Comment by brice-morin** [comment]
now almost 100% sure it is related to internal ports in posix. It works if I split the port into two "normal" port and connect them myself in the configuration (so, it is a ThingML bug)
